speakez/speakez/urls.py
from speakez_core import views
from django.views.generic import RedirectView
from django.urls import include, path
from rest_framework import routers
from speakez_core import views
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path(r'', RedirectView.as_view(url='/accounts/login/'), name='admin'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/create_user/', views.create_user, name='new_user'),
    path('accounts/users/', views.user_list, name='user_list'),
    path('accounts/users/<str:username>/', views.UserDetail.as_view(), name='user_detail'),
    path('admin/view_users/<str:username>/delete_user/', views.DeleteUser.as_view(), name='delete_user'),
    path('admin/', views.dashboard, name='dashboard'),
    path('admin/edit_recipients/', views.edit_recipients, name='edit_recipient'),
    path('admin/edit_recipients/<uuid:recipient_id>/', views.recipients_detail, name='recipient_detail'),
    path('admin/view_recipients/', views.list_recipients, name='recipient_list'),
    path('admin/select_recipients/', views.select_recipients, name='select_recipients'),
    path('admin/delete_recipients/', views.delete_recipient, name='delete_recipient'),
    path('admin/select_recipients/select_message/<recipients>/', views.select_message, name='select_message'),
    path('admin/call_recipients/', views.call_recipients, name='call_recipients'),
    path('admin/view_report/', views.view_report, name='view_report'),
    path('admin/view_report/<uuid:call_log_id>/', views.view_report_detail, name='view_report_detail'),
    path('admin/add_messages/', views.add_message, name='add_message'),
    path('admin/add_category/', views.add_category, name='add_category'),
    path('admin/view_messages/<uuid:call_message_id>/', views.call_message_detail, name='update_message_detail'),
    path('admin/delete_messages/', views.delete_message, name='delete_message'),
    path('admin/view_messages/', views.list_call_messages, name='message_list'),
    path('admin/audio/<path:filename>/', views.get_audio_file, name='get_audio_file'),
    path('audio_message/<key>/', views.get_audio_message, name='get_audio_message'),
    path('twilio/call_status_event/', views.save_call_status, name='save_call_status'),
    path('twilio/debug/', views.view_callback),
    # url(r'^', RedirectView.as_view(url='/accounts/login/'))
    # this redirect will not allow websever to serve message from media file.
    # use 404 redirect page instead
]
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

speakez/speakez_core/models.py
from django.db import models
import uuid
from datetime import datetime
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.contrib.postgres.fields import JSONField
from django.core.validators import FileExtensionValidator

# Create your models here.

class Refugee(models.Model):
    class Meta:
        verbose_name = 'Refugee'
        verbose_name_plural = "Refugees"

    SINGLE = 'single'
    MARRIED = 'married'
    MARTIAL_STATUSES = (
        (SINGLE, 'Single'),
        (MARRIED, 'MARRIED'),
    )

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    first_name = models.CharField(_("First Name"), max_length=250, blank=False, null=False)
    middle_name = models.CharField(_("Middle Name"), max_length=250, blank=True, null=True)
    last_name = models.CharField(_("Last Name"), max_length=250, blank=False, null=False)
    gender = models.CharField(_("Gender"), max_length=100, blank=True, null=True)
    age = models.PositiveIntegerField(_("Age"), default=0)

    phone_number = models.CharField(_("Phone Number"), max_length=25, blank=False, null=False)
    demographic_info = models.CharField(_("Demographic Info"), max_length=250, blank=True, null=True)
    ethnicity = models.CharField(_("Ethinicity"), max_length=250, blank=True, null=True)

    # Address
    street_number = models.CharField(_("Street Number"), max_length=30, blank=True, null=True)
    street_name = models.CharField(_("Street Name"), max_length=150, blank=True, null=True)
    city = models.CharField(_("City"), max_length=200, blank=True, null=True)
    zip_code = models.CharField(_("ZIP Code"), max_length=10, blank=True, null=True)

    emergency_contact = models.CharField(_("Emergency Contact"), max_length=300, blank=True, null=True)
    martial_status = models.CharField(max_length=9, choices=MARTIAL_STATUSES, default=SINGLE)

    date_time_created = models.DateTimeField(_("Date and Time Created"), default=timezone.now)
    date_time_edited = models.DateTimeField(_("Date and Time Edited"), auto_now=timezone.now)
    deleted = models.BooleanField(_("Deleted"), default=0)

    def __str__(self):
        return self.last_name + ', ' + self.first_name

    def get_name(self):
        return self.first_name + " " + self.middle_name + " " + self.last_name

    def get_refugee_id(self):
        return self.id


class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = "Categories"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False) 
    date_time_created = models.DateTimeField(_("Date and Time Created"), default=timezone.now)
    title = models.CharField(_("Title"), max_length=250)

    def __str__(self):
        return self.title


class CallMessage(models.Model):
    class Meta:
        verbose_name = 'Call Message'
        verbose_name_plural = "Call Messages"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    date_time_created = models.DateTimeField(_("Date and Time Created"), default=timezone.now)
    date_time_edited = models.DateTimeField(_("Date and Time Edited"), auto_now=timezone.now)
    deleted = models.BooleanField(_("Deleted"), default=0)
    duration = models.FloatField(_("Duration in seconds"))
    title = models.CharField(_("Title"), max_length=250)
    content = models.TextField(_("Content"), blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    audio = models.FileField(_("Audio"), upload_to='uploads/', validators=[FileExtensionValidator(allowed_extensions=['wav'])], blank=True, null=True)

    def __str__(self):
        return self.title


class CallLog(models.Model):
    class Meta:
        verbose_name = 'Call Log'
        verbose_name_plural = "Call Logs"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    admin_id = models.CharField(_("caller id"), max_length=250, blank=False, null=False)
    admin_username = models.CharField(_("caller username"), max_length=250, blank=False, null=False)
    date_time_created = models.DateTimeField(_("Date and Time Created"), default=timezone.now)
    message_sent = models.ForeignKey(CallMessage, on_delete=models.CASCADE)

 

class CallLogDetail(models.Model):
    class Meta:
        verbose_name = 'Call Log Detail'
        verbose_name_plural = "Call Log Details"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    recipient = models.ForeignKey(Refugee, on_delete=models.CASCADE)
    call_sid = models.CharField(_("twilio call sid"), max_length=34, blank=False, null=False)
    call_log = models.ForeignKey(CallLog, on_delete=models.CASCADE)


class CallStatus(models.Model):
    class Meta:
        verbose_name = 'Call Status'
        verbose_name_plural = "Call Statuses"

    Called = models.CharField(_("phone number being called"), max_length=64)
    ToState = models.CharField(_(""), max_length=64)
    CallerCountry = models.CharField(_(""), max_length=64)
    Direction = models.CharField(_(""), max_length=64)
    Timestamp = models.CharField(_(""), max_length=64)
    CallbackSource = models.CharField(_(""), max_length=64)
    SipResponseCode = models.CharField(_(""), max_length=64)
    CallerState = models.CharField(_(""), max_length=64)
    ToZip = models.CharField(_(""), max_length=64)
    SequenceNumber = models.CharField(_(""), max_length=64)
    CallSid = models.CharField(primary_key=True, max_length=64)
    To = models.CharField(_(""), max_length=64)
    CallerZip = models.CharField(_(""), max_length=64)
    ToCountry = models.CharField(_(""), max_length=64)
    CalledZip = models.CharField(_(""), max_length=64)
    ApiVersion = models.CharField(_(""), max_length=64)
    CalledCity = models.CharField(_(""), max_length=64)
    CallStatus = models.CharField(_(""), max_length=64)
    Duration = models.CharField(_(""), max_length=64)
    From = models.CharField(_(""), max_length=64)
    CallDuration = models.CharField(_(""), max_length=64)
    AccountSid = models.CharField(_(""), max_length=64)
    CalledCountry = models.CharField(_(""), max_length=64)
    CallerCity = models.CharField(_(""), max_length=64)
    ToCity = models.CharField(_(""), max_length=64)
    FromCountry = models.CharField(_(""), max_length=64)
    Caller = models.CharField(_(""), max_length=64)
    FromCity = models.CharField(_(""), max_length=64)
    CalledState = models.CharField(_(""), max_length=64)
    FromZip = models.CharField(_(""), max_length=64)
    AnsweredBy = models.CharField(_(""), max_length=64)
    FromState = models.CharField(_(""), max_length=64)

speakez/speakez_core/forms.py
from django.forms import ModelForm, Textarea, CheckboxSelectMultiple
from .models import CallMessage, Category, Refugee, CallStatus

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit



class CallMessageForm(ModelForm):
    class Meta:
        model = CallMessage
        fields = ['duration', 'title', 'category','content', 'audio','deleted']
        widgets = {
            'content': Textarea(attrs={'cols': 60, 'rows': 10}),
        }


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

class RefugeeForm(ModelForm):
    class Meta:
        model = Refugee
        fields = ('first_name','middle_name','last_name','gender','age','phone_number','demographic_info','ethnicity',
        'street_number','street_name','city','zip_code','emergency_contact','martial_status')
        
class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = ['title']
        
class CallStatusForm(ModelForm):
    class Meta:
        model = CallStatus
        fields = '__all__'

speakez/speakez_core/templates/message/add_category.html
{% extends 'base.html' %}
{% load fontawesome %}
{% load crispy_forms_tags %}

{% block title %}Add Category{% endblock %}

{% block content %}
<div>
    
<form id="category" class="text-left" method="POST"> {% csrf_token %}
    {{ form|crispy }}
    <button id="submit" type="submit" class="btn btn-primary">Submit</button>
</form>

</div>
{% endblock %}

speakez/speakez_core/templates/message/edit_message.html
{% extends 'base.html' %}
{% load fontawesome %}
{% load static %}

{% block title %}Record/Edit an Audio Message{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<div class="dashboard">
    
    <div class="row body text-left">
        <div>
        {% if is_update %}
            <audio style="width:75%" controls src="/admin/audio/{{ message.audio.name }}/" type="audio/wav" id="audio"></audio>
        {% else %}
            <audio style="width:75%" controls autoplay id="audio"></audio>
        {% endif %}
            <div class="row justify-content-around">
                <button class="col-sm-3 btn btn-primary js-start">{% fontawesome_icon 'microphone' %}</button>
                <button class="col-sm-3 btn btn-primary js-stop" disabled>{% fontawesome_icon 'square' %}</button>
                <button class="col-sm-2 btn btn-primary">{% fontawesome_icon 'circle' %}</button>
            </div>
            <br>
            <!-- <input id="id_audio" hidden> -->

            <form class="row-no-padding" method="POST" 
            {% if is_update %} 
            action="{% url 'update_message_detail' message.id %}"
            {% else %}
            action="{% url 'add_message' %}"
            {% endif %} 
            enctype="multipart/form-data"> {% csrf_token %}
                <div>
                    {{ form.category|as_crispy_field }}
                    Add New Category: &nbsp; <button type="button" class="btn btn-primary" onclick="add_category()"><i class="fa fa-plus" aria-hidden="true"></i></button>
                    {{ form.title|as_crispy_field }}
                </div>
                <div>
                    {{ form.content|as_crispy_field }}
                </div>
                <input class="btn btn-primary col-sm-2" type="submit">
            </form>
        </div>
    </div>

</div>

<script>
    function add_category(){
        window.location = `/admin/add_category/`
    }
</script>
<script src="{% static "js/recorder.js" %}"></script>
<script src="https://cdn.webrtc-experiment.com/MediaStreamRecorder.js"> </script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
<script src="{% static "js/message.js" %}"></script>
{% endblock content %}

speakez/speakez_core/templates/message/message_detail.html
{% extends 'base.html' %}
{% load fontawesome %}

{% block title %}View Messages{% endblock %}

{% block content %}

<div class="dashboard">
    
<h1>{{ message.title }}</h1>
<ul>
    <li>Date and Time Created: {{message.date_time_created}}</li>
    <li>Duration: {{message.duration}} seconds</li>
    <li>Content: {{message.content}}</li>
    <li>Category/Categories:</li>
{% for category in message.category.all %}
    {{ category.title }}
{% endfor %}
    <li>Audio: {{message.audio}}</li>
</ul>

</div>
{% endblock %}

speakez/speakez_core/templates/message/message_list.html
{% extends 'base.html' %}
{% load fontawesome %}

{% block title %}View Messages{% endblock %}

{% block content %}

<div class="dashboard" style="min-width: 900px;">
    
{% if messages %}
    <table id="messages" class="table table-striped table-bordered clickable-row" width="100%">
        <thead>
            <tr>
                <th>Name</th>
                <th>Contact</th>
                <th>Audio</th>
                <th>Duration</th>
                <th>Content</th>
                <th>Actions</th>
            </tr>
        </thead>
    </table>
{% else %}
    <p>No messages are available.</p>
{% endif %}

<div class="row" style="display: flex; justify-content: center;">
        <button type="button" name="home" id="home" class="btn btn-primary" style="margin-right: 20px;" onclick="goHome()" btn-lg btn-block">Home</button>
        <button type="button" name="send" id="send" class="btn btn-primary" onclick="goSend()" btn-lg btn-block">Go to Send Page</button>
</div>


</div>
<script type="application/javascript">
    let dataSet = {{messages|safe}}
    console.log(dataSet)

    $(document).ready(function () {
        let table = $('#messages').DataTable({
            data: dataSet,
            columns: [
                {
                    mRender : function ( data, type, row ) { 
                    return `${row.title}`}
                },
                {  
                    mRender : function ( data, type, row ) { 
                    return `${row.category}`}
                },
                {  
                    mRender : function ( data, type, row ) { 
                    return `<audio style="width:100%" controls id="${row.pk}" src='/admin/audio/${row.audio_name}/'>`
                    },
                    width: "45%",
                },
                {  
                    mRender : function ( data, type, row ) { 
                    return `${row.duration} seconds`}
                },
                {  
                    mRender : function ( data, type, row ) { 
                    return `${row.content}`}
                },
                {  
                    mRender : function ( data, type, row ) { 
                    return `<button type="button" name="delete-${row.id}" id="delete-${row.id}" onclick="onDelete('${row.id}')" class="btn btn-primary" btn-lg btn-block">Delete</button>`}
                },
            ]
        });
        $('#messages tbody').on( 'click', 'td', function () {
            let idx = table.cell(this).index().row;
            var id = table.row( idx ).data().id
            window.location.href = `${id}/`;
        });
    });

    function goHome() {
        window.location.href = '/admin/';
    }

    function goSend() {
        window.location.href = '/admin/select_recipients/';
    }

    function onDelete(massage_id) {
        $.ajax({
            type: "POST",
            url: '/admin/delete_messages/',
            data: {
                'id': massage_id,
            },
            success: function(data) {
                window.location.href = '/admin/view_messages';
            },
            error: function (xhr, ajaxOptions, thrownError) {
                alert(xhr.status);
                console.log(thrownError)
            },
        });
    }

</script>
{% endblock %}